version: "3.9"
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: devenv-mock-api
    ports:
      - "10000:8080"
    volumes:
      - ./doc:/usr/share/nginx/html/doc
    environment:
      API_URL: doc/swagger.yaml