openapi: 3.0.1
info:
  title: MiniTodoAPI
  version: '1.0'
paths:
  /:
    get:
      tags:
        - MiniTodoAPI
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: string
  /todos:
    get:
      tags:
        - MiniTodoAPI
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ToDo'
              examples:
                todoone:
                  value: |-
                    [
                      {
                        "id": 1,
                        "text": "string",
                        "status": "string"
                      },
                      {
                        "id": 2,
                        "text": "string2",
                        "status": "string2"
                      },
                      {
                        "id": 3,
                        "text": "string2",
                        "status": "string2"
                      }
                    ]
    post:
      tags:
        - MiniTodoAPI
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ToDo'
      responses:
        '200':
          description: Success
    put:
      tags:
        - MiniTodoAPI
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ToDo'
      responses:
        '200':
          description: Success
  /todos/{id}:
    get:
      tags:
        - MiniTodoAPI
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToDo'
              examples:
                getsingleitem:
                  value: |-
                    {
                      "id": 1,
                      "text": "string",
                      "status": "string"
                    }
    delete:
      tags:
        - MiniTodoAPI
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
components:
  schemas:
    ToDo:
      type: object
      properties:
        id:
          type: integer
          format: int32
        text:
          type: string
          nullable: true
        status:
          type: string
          nullable: true
      additionalProperties: false
